# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:6.0.20
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: unisan-server
      MONGO_INITDB_ROOT_PASSWORD: yourDbPassword
      MONGO_INITDB_DATABASE: unisan-server
    volumes:
      - ./dump:/etc/dumps

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: unisan-server
      ME_CONFIG_MONGODB_ADMINPASSWORD: yourDbPassword
      ME_CONFIG_MONGODB_URL: mongodb://unisan-server:yourDbPassword@mongo:27017/
      ME_CONFIG_BASICAUTH: false
